### ISSUE TITLE
Improving the accessibility of Berusky2's pak files

### ISSUE THREAD

**Issue by apoleon** [stransky/berusky2#12]
It would be nice if Berusky2's data files (*.pak) would be more accessible thus users could modify them more easily. 

I'm thinking about
1. Some sort of documentation that explains how to extract the pak files with free software tools.
2. Getting rid of the pak files completely so that game data would only consist of editable graphic (svg, png, bmp, tga) and sound (ogg, wav) files.
3. Making all graphics and data files extra availabe for download like this is already achieved with Berusky2's soundtrack.

**Comment by stransky** [comment]
Asher already did that, the file is now available as separated files (0.12).
